name: BAT cov

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  cov:
    name: Coverage
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
      - name: Setup
        uses: actions/setup-node@v4
        with:
          node-version: 26.1.0
          cache: 'npm'
          cache-dependency-path: '**/package-lock.json'
      - name: Install
        run: npm ci --prefer-offline --no-audit --no-fund
      - name: Test
        run: npm run cov-ci
        timeout-minutes: 10
      - name: Upload Coverage to Codecov
        uses: codecov/codecov-action@v4
        if: false
        with:
          files: ./coverage/lcov.info
